import Head from "next/head";

import RatingBar from "@/components/Bar/RatingBar";
import Pricing from '../components/services/Pricing'
import TopRatedProfessionals from "@/components/carousel/TopRatedProfessionals";
import WebSolutions from "@/components/WebSolutions/WebSolutions";
import Intro from "@/components/main/Intro";
const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <RatingBar />
      <WebSolutions />

      <TopRatedProfessionals
        backgroundColor="#eeeeee"
        title="Get top-rated and recognized professionals onboard!"
        slidesToShow={4}
        slidesToScroll={1}
      />
      <Pricing/>
    </>
  );
};
export default Home;
