import Head from "next/head";

import RatingBar from "@/components/Bar/RatingBar";
import Pricing from '../components/services/Pricing'
import TopRatedProfessionals from "@/components/carousel/TopRatedProfessionals";
import WebSolutions from "@/components/WebSolutions/WebSolutions";
import Intro from "@/components/main/Intro";
import { Fade } from "react-awesome-reveal";
import OurDesigns from "@/components/ourDesigns/OurDesigns";

const Home = () => {
 
  return (
    <>
   
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Intro />
      <RatingBar />
      <WebSolutions />
      <OurDesigns/>
      <WebSolutions  />
      <TopRatedProfessionals
        backgroundColor="#eeeeee"
        title="Get top-rated and recognized professionals onboard!"
        slidesToShow={4}
        slidesToScroll={1}
      />
      <Pricing/>
    </>
  );
};
export default Home;
export async function getServerSideProps(context) {
  return {
    props: {
      metaData: {
        title:
          "Custom Mobile App Development Agency &amp; Mobile Application Design Services in USA | Mobile Application Development Company",
        description:
          "9solutions is a mobile app and software development company elevating local businesses through top-notch strategy and design.",
        keywords:
          "Custom Mobile App Development Agency &amp; Mobile Application Design Services in USA | Mobile Application Development Company",
        publishTime: new Date().toISOString(),
        // image: `${process.env.eforte_blog_url}/uploads/eForte_icon.png`,
      },
    },
  };
}