export const web = [
    {
      title: "Basic",
      subtitle: "WEB PACKAGE",
      price: 199,
      oldPrice: "666",
      items: [
        "3 Page Website", 
        "2 Stock Images",
        "1 jQuery Slider Banner",
        "Contact/Query Form",
        "48 to 72 hours TAT",
        "Complete Development",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "Professional",
      subtitle: "WEB PACKAGE",
      price: 699,
      oldPrice: "1900",
      items: [
        "10 Unique Pages Website",
        "CMS / Admin Panel Support",
        "12 Stock images",
        "5 Banner Designs",
        "1 jQuery Slider Banner",
        "FREE Google Friendly Sitemap",
        "48 to 72 hours TAT",
        "Complete Deployment",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "Elite",
      subtitle: "WEB PACKAGE",
      price: 1299,
      oldPrice: "4,400",
      items: [
        "Upto 15 Unique Pages Website",
        "Conceptual and Dynamic Website",
        "Mobile Responsive",
        "Online Reservation/Appointment Tool (Optional)",
        "Online Payment Integration (Optional)",
        "Custom Forms",
        "Lead Capturing Forms (Optional)",
        "Striking Hover Effects",
        "Newsletter Subscription (Optional)",
        "Newsfeed Integration",
        "Social Media Integration",
        "Search Engine Submission",
        "5 Stock Photos",
        "3 Unique Banner Design",
        "48 to 72 hours TAT",
        "Complete Deployment",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
  ];
export const ecom = [
    {
      title: "Kickstarter",
      subtitle: "E-COMMERCE",
      price: 600,
      oldPrice: "1,200",
      items: [
        "Up-to 100 Products",
        "Content Management System (CMS)",
        "Mini Shopping Cart Integration",
        "Payment Module Integration",
        "Easy Product Search",
        "Dedicated designer & developer",
        "Unlimited Revisions",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "Dynamic",
      subtitle: "E-COMMERCE",
      price: "1,394",
      oldPrice: "2,788",
      items: [
        "Customized Design",
        "Up-to 500 Products",
        "Content Management System (CMS)",
        "Full Shopping Cart Integration",
        "Payment Module Integration",
        "Easy Product Search",
        "Product Reviews",
        "5 Promotional Banners",
        "Unlimited Revisions",
        "Team of Expert Designers & Developers",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "High-End",
      subtitle: "E-COMMERCE",
      price: "3,694",
      oldPrice: "7,388",
      items: [
        "Unlimited Pages Website with Unique Design",
        "UNLIMITED Logo Design Concepts",
        "By 6 Award Winning Designers",
        "Icon Design",
        "UNLIMITED Revisions",
        "Print Media",
        "Stationary Design (BusinessCard,Letterhead & Envelope)",
        "Invoice Design, Email Signature",
        "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
        "Product Catalog Design",
        "Sign age Design (OR) Label Design",
        "T-Shirt Design (OR) Car Wrap Design",
        "Website",
        "E-Commerce Store Design",
        "Product Detail Page Design",
        "Unique Banner Slider",
        "Featured Products Showcase",
        "Full Shopping Cart Integration",
        "Unlimited Products",
        "Unlimited Categories",
        "Product Rating & Reviews",
        "Easy Product Search",
        "Payment Gateway Integration",
        "Multi-currency Support",
        "Content Management System",
        "Cutomer Log-in Area",
        "Mobile Responsive",
        "Social Media Plugins Integration",
        "Tell a Friend Feature",
        "Social Media Pages",
        "Facebook , Twitter, YouTube, Google+ & Pinterest Page Designs",
        "Value Added Services",
        "Dedicated Account Manager",
        "Unlimited Revisions",
        "All Final File Formats",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
  ];
export const logo = [
    {
      title: "Basic",
      subtitle: "LOGO DESIGN",
      price: 39,
      oldPrice: "120",
      items: [
        "2 Custom Logo Design Concepts",
        "1 Dedicated Designer",
        "4 REVISIONS",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "Startup",
      subtitle: "LOGO DESIGN",
      price: 79,
      oldPrice: "250",
      items: [
        "5 Custom Logo Design Concepts",
        "By 2 Designers",
        "UNLIMITED Revisions",
        "48 to 72 hours TAT",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
    {
      title: "Professional",
      subtitle: "LOGO DESIGN",
      price: 129,
      oldPrice: "410",
      items: [
        "UNLIMITED Logo Design Concepts",
        "By 4 Designers",
        "UNLIMITED Revisions",
        "Stationary Design (Business Card, Letterhead, Envelope)",
        "48 to 72 hours TAT",
        "FREE MS Word Letterhead",
        "All Final Files Format (AI, PSD, EPS, PNG, GIF, jpeg, PDF)",
        "100% Ownership Rights*",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
      ],
    },
  ];
export const seo = [
    {
      title: "Startup Plan",
      subtitle: "SEARCH ENGINE OPTIMIZATION",
      price: 350,
      oldPrice: "700",
      items: [
        "Campaign Setup And Optimization",
        "Website Audit",
        "Pages Optimized (10 pages)",
        "Keyword Research",
        "Keyword Grouping",
        "Keyword Mapping",
        "On-Page Optimization",
        "SEO Road Map",
        "Blog Creation",
        "Webpage Copywriting (3 pages , 350 words per page)",
        "Meta Description Optimization (10 meta description)",
        "Meta Keyword Optimization (10 meta keywords)",
        "Domain Redirect Optimization (10 domain redirects)",
        "xml Sitemap Optimization",
        "Robots.txt Check",
        "URL Rewrites (10 URL rewrites)",
        "Broken Link Report",
        "Rich Snippet Recommendations",
        "Breadcrumbs",
        "Social Bookmarking",
        "Slide Share Marketing",
        "Forums/FAQ’s",
        "Link Building",
        "Directory Submission",
        "Local Business Listings",
      ],
    },
    {
      title: "Scaling Plan",
      subtitle: "SEARCH ENGINE OPTIMIZATION",
      price: 700,
      oldPrice: "1,400",
      items: [
        "Business Analysis",
        "Consumer Analysis",
        "Competitor Analysis",
        "15 Pages Keyword Targeted",
        "Webpage Optimization",
        "Meta Tags Creation",
        "Keyword Optimization",
        "Image Optimization",
        "Tracking & Analysis",
        "Google Analytics Installation",
        "Google Webmaster Installation",
        "Call To Action Plan",
        "Creation of Sitemaps",
        "Reporting",
        "Monthly Reporting",
        "Recommendation",
        "Email Support",
        "Phone Support",
        "Off Page Optimization",
        "Social Bookmarking",
        "Slide Share Marketing",
        "Forums/FAQ’s",
        "Link Building",
        "Directory Submission",
        "Local Business Listings",
      ],
    },
    {
      title: "Venture Plan",
      subtitle: "SEARCH ENGINE OPTIMIZATION",
      price: 1200,
      oldPrice: "2,400",
      items: [
        "Prior Analysis",
        "Business Analysis",
        "Consumer Analysis",
        "Competitor Analysis",
        "30 Pages Keyword Targeted",
        "Webpage Optimization",
        "Meta Tags Creation",
        "Keyword Optimization",
        "Image Optimization",
        "Inclusion of anchors Tags",
        "Inclusion of anchors Indexing Modifications",
        "Tracking & Analysis",
        "Google Places Inclusions",
        "Google Analytics Installation",
        "Google Webmaster Installation",
        "Call To Action Plan",
        "Creation of Sitemaps",
        "Reporting",
        "Monthly Reporting",
        "Recommendation",
        "Email Support",
        "Phone Support",
        "Off Page Optimization",
        "Social Bookmarking",
        "Slide Share Marketing",
        "Forums/FAQ’s",
        "Link Building",
        "Directory Submission",
        "Local Business Listings",
      ],
    },
  ];

  export const branding = [
    {
      title: "Stationary",
      subtitle: "BRANDING",
      price: 99,
      oldPrice: "370",
      items: [
        "1 Business Card Design",
        "1 Letterhead Design",
        "1 Envelope Design",
        "Dedicated Designer",
        "3 Design Revisions",
        "Turnaround Time 24 - 48 Hours",
        "Features:",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
        "All Final File Formats",
      ],
    },
    {
      title: "Brochure/Flyer",
      subtitle: "BRANDING",
      price: "149",
      oldPrice: "299",
      items: [
        "2 Design Concepts (Trifold / Bi-fold)",
        "Dedicated Designer",
        "Dedicated Account Manager",
        "Unlimited Revisions",
        "Turnaround Time - 48 - 72 Hours",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
        "All Final File Formats",
      ],
    },
    {
      title: "Poster Design",
      subtitle: "BRANDING",
      price: "299",
      oldPrice: "700",
      items: [
        "1 Unique Design",
        "3 Design Concepts",
        "Dedicated Designer",
        "2 Design Revisions",
        "Turnaround Time - 48 - 72 Hours",
        "Features:",
        "100% Satisfaction Guarantee",
        "100% Unique Design Guarantee",
        "100% Money Back Guarantee",
        "All Final File Formats",
      ],
    },
  ];